### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Djodo** [t0mg/reacticz#102]
Hello I use Reacticz on a touchpad hanging on the wall. The problem is that we can not see the text. So I submit an idea for developers: add an option to enlarge or reduce the font size of cells

**Comment by davidlb** [comment]
I did some tests, one simple and quick solution would be to use the css property zoom in the body but it's not supported in Firefox. Using the css property transform:scale gives weird behaviors. I keep working on it.

**Comment by t0mg** [comment]
Awesome, thanks @davidlb!

**Comment by t0mg** [comment]
Fixed!
