### ISSUE TITLE
Dummy device Alert

### ISSUE THREAD

**Issue by papo-o** [t0mg/reacticz#18]
Dummy devices alert return Unsupported type: {"Battery":255,"RSSI":12,"description":"","
![alerts](https://cloud.githubusercontent.com/assets/25136535/21998248/f8c7bbcc-dc33-11e6-99cb-49c7be0f0005.png)
![alerts2](https://cloud.githubusercontent.com/assets/25136535/21998251/feaca8d6-dc33-11e6-86fb-f3385be795cd.png)
 five levels : 0 (grey), 1(green),2(yellow),3(orange),4(red) 
The json request return :
{
   "ActTime" : 1484598897,
   "ServerTime" : "2017-01-16 21:34:57",
   "Sunrise" : "08:32",
   "Sunset" : "17:36",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "-5.1",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 14,
         "HardwareName" : "Capteurs Virtuels",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "82697",
         "LastUpdate" : "2017-01-16 21:34:15",
         "Level" : 4,
         "Name" : "Givre",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Alert",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "Alert",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "563",
         "YOffset" : "376",
         "idx" : "698"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by t0mg** [comment]
Le message
Unsupported type: {"Battery":255,"RSSI":12,"description":"","
est tronqué (c'est ma faute le widget est trop petit)

Est ce que tu peux essayer de sélectionner toute la ligne en double-cliquant au niveau du début du message debug (battery blabla) et en faisant CTRL+C ? Ça fonctionne chez moi. Sinon en agrandissant le widget ou enfin en faisant un clic droit>inspecter

Merci !

**Comment by papo-o** [comment]
avec la fonction inspecter
{"Battery":255,"RSSI":12,"description":"","dtype":"General","id":"82698","idx":699,"name":"Alerte Pluie","nvalue":1,"stype":"Alert","svalue1":"Pas de précipitations","unit":1}
