### ISSUE TITLE
Dimmer can't be switched on/off on iOS

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#23]
On iOS it is not possible anymore to switch a dimmer on or off.
A RGWB light can still be switched on or off on iOS (the same goes for a normal switch).

I think the dimmer worked before the change of the MaxDimLevel.

**Comment by t0mg** [comment]
Ok thanks for the report. Can you give me more details on what is happening ? You cannot set any value at all?

**Comment by gerard33** [comment]
If I press the button on iOS it won't turn on or off.
I also can't change the dimlevel.

Let me know if I can need something to test in the code using the development mode.

**Comment by t0mg** [comment]
I have no idea :(
It still works on Safari so that's not helping either.

**Comment by t0mg** [comment]
I'm gonna have to try with the xcode emulator, I'll keep you posted.

**Comment by gerard33** [comment]
I tried with an older code (https://github.com/t0mg/reacticz/blob/9abced874bb31f78fe3d6ef4c73101fbf37bb5e5/src/widgets/SwitchDimmer.js) but still not working.
Also using Chrome on iOS is not working. Strange this.
Let me know if I have to test anything.

**Comment by t0mg** [comment]
Ok I can reproduce on xcode emulator, it's completely broken. Basically there is an invisible slider over the widget that should take up the whole space. In iOS it doesn't work, you have to find the invisible dot and drag it:

![screen-shot-2017-01-19-at-1 46 39-am](https://cloud.githubusercontent.com/assets/1903597/22089114/3f87a8cc-dde9-11e6-9580-b004899b1925.png)

I need more time to find out how to fix that, sorry for the trouble (also: it was always like that, so I don't understand how you managed to make it work originally)

**Comment by gerard33** [comment]
I tried with an older version of the code (see post above) and that is indeed not working as well.
I probably thought I used  this before on my phone, which can't be the case :-)

After some more testing on iOS I am sometimes able to dim, but it takes a lot of patience and a the switch must already be on in Reacticz.

**Comment by gerard33** [comment]
It is working now! Thanks for fixing this, even without an iOS device :-)

**Comment by t0mg** [comment]
Yay! :)
