### ISSUE TITLE
Unsupported type: kWh

### ISSUE THREAD

**Issue by papo-o** [t0mg/reacticz#26]
{"Battery":255,"RSSI":12,"description":"","dtype":"General","id":"00000D01","idx":769,"name":"Frigo (Consommation)","nvalue":0,"stype":"kWh","svalue1":"154.320","svalue2":"190990.000","unit":1}
![image](https://cloud.githubusercontent.com/assets/25136535/22126212/0c80969c-de97-11e6-8ad3-8e038403a99c.png)

json request result :
{
   "ActTime" : 1484861436,
   "ServerTime" : "2017-01-19 22:30:36",
   "Sunrise" : "08:30",
   "Sunset" : "17:40",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CounterToday" : "1.680 kWh",
         "CustomImage" : 0,
         "Data" : "191.010 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 17,
         "HardwareName" : "Zwave USB",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "00000D01",
         "LastUpdate" : "2017-01-19 22:29:54",
         "Name" : "Frigo (Consommation)",
         "Notifications" : "false",
         "Options" : "",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "kWh",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "current",
         "Unit" : 1,
         "Usage" : "154.1 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "769"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by t0mg** [comment]
Looks like the value for CounterToday is not available in the MQTT message. Instant and total are in there though, would that be enough ?

**Comment by papo-o** [comment]
yes
