### ISSUE TITLE
WindMeter

### ISSUE THREAD

**Issue by deennoo** [t0mg/reacticz#28]
Just test it, a great Work !

got a wind meter not reconize yet

Unsupported type: Weather Station
{"Battery":100,"RSSI":12,"description":"","dtype":"Wind","id":"6900","idx":1332,"name":"Anemometre","nvalue":0,"stype":"Weather Station","svalue1":"259.00","svalue2":"W","svalue3":"11","svalue4":"15","svalue5":"0.0","svalue6":"0.0","unit":0}

Can you add it please ?

**Comment by t0mg** [comment]
Can you show me as screenshot of your dashboard or explain what each svalue means ?

**Comment by papo-o** [comment]
If my case can serve
![anemometre](https://cloud.githubusercontent.com/assets/25136535/22266328/ee4cb3ee-e27f-11e6-9003-3d9439397702.png)
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "337.00;NNW;0;0;0.0;0.0",
Description: "",
Direction: 337,
DirectionStr: "NNW",
Favorite: 0,
Gust: "0.0",
HardwareID: 13,
HardwareName: "RFXCOM",
HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
HardwareTypeVal: 1,
HaveTimeout: false,
ID: "BA00",
LastUpdate: "2017-01-24 21:57:37",
Name: "anémometre",
Notifications: "false",
PlanID: "7",
PlanIDs: [
7
],
Protected: false,
ShowNotifications: true,
SignalLevel: 6,
Speed: "0.0",
SubType: "WGR800",
Timers: "false",
Type: "Wind",
TypeImg: "wind",
Unit: 0,
Used: 1,
XOffset: "472",
YOffset: "18",
idx: "741"
}

**Comment by gerard33** [comment]
I implemented a wind widget with pull request #45.
