### ISSUE TITLE
Dimmer with steps 1-100

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#3]
The dimmer function in Reacticz is working fine for my Hue lights (white color only).
The maxdimlevel of these Hue lights is 15 (see json output below).
But I also have a Zwave dimmer which can be dimmed from 1-100 in steps of 1, so the maxdimlevel is 100 (see json output below).

Is it possible to check the maxdimlevel of the light and dependend on that, send the right value to Domoticz?

JSON output Hue light
`{
   "ActTime" : 1483916702,
   "ServerTime" : "2017-01-09 00:05:02",
   "Sunrise" : "08:44",
   "Sunset" : "16:41",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 134,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "Hue",
         "HardwareType" : "Philips Hue Bridge",
         "HardwareTypeVal" : 38,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0000004",
         "Image" : "PhilipsHueRGBBulb",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-01-08 23:59:04",
         "Level" : 60,
         "LevelInt" : 9,
         "MaxDimLevel" : 15,
         "Name" : "Hue kantoor",
         "Notifications" : "false",
         "PlanID" : "20",
         "PlanIDs" : [ 20 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "392"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

JSON output ZWave dimmer
`{
   "ActTime" : 1483916592,
   "ServerTime" : "2017-01-09 00:03:12",
   "Sunrise" : "08:44",
   "Sunset" : "16:41",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "ZWave",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001601",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-01-08 23:59:11",
         "Level" : 15,
         "LevelInt" : 15,
         "MaxDimLevel" : 100,
         "Name" : "Lamp kantoor",
         "Notifications" : "false",
         "PlanID" : "20",
         "PlanIDs" : [ 20 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "376"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

**Comment by mjf2708** [comment]
Similar issue applies to LightwaveRF dimmer, which has 32 levels - MaxDimLevel: ​32 (96%). See JSON output below.
`{
    "ActTime": ​1484071080,
    "ServerTime": "2017-01-10 17:58:00",
    "Sunrise": "08:07",
    "Sunset": "16:14",
    "result": 
[
{
    "AddjMulti": ​1.0,
    "AddjMulti2": ​1.0,
    "AddjValue": ​0.0,
    "AddjValue2": ​0.0,
    "BatteryLevel": ​255,
    "CustomImage": ​0,
    "Data": "Set Level: 96 %",
    "Description": "",
    "Favorite": ​0,
    "HardwareID": ​2,
    "HardwareName": "RFXCOM",
    "HardwareType": "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
    "HardwareTypeVal": ​1,
    "HaveDimmer": true,
    "HaveGroupCmd": true,
    "HaveTimeout": false,
    "ID": "F0BEE7",
    "Image": "Light",
    "IsSubDevice": false,
    "LastUpdate": "2017-01-10 17:57:56",
    "Level": ​96,
    "LevelInt": ​31,
    "MaxDimLevel": ​32,
    "Name": "Study ceiling",
    "Notifications": "false",
    "PlanID": "2",
    "PlanIDs": 
            [
                ​2
            ],
            "Protected": false,
            "ShowNotifications": true,
            "SignalLevel": "-",
            "Status": "Set Level: 96 %",
            "StrParam1": "",
            "StrParam2": "",
            "SubType": "LightwaveRF",
            "SwitchType": "Dimmer",
            "SwitchTypeVal": ​7,
            "Timers": "false",
            "Type": "Lighting 5",
            "TypeImg": "dimmer",
            "Unit": ​8,
            "Used": ​1,
            "UsedByCamera": false,
            "XOffset": "168",
            "YOffset": "356",
            "idx": "118"
        }
    ],
    "status": "OK",
    "title": "Devices"
}`

**Comment by gerard33** [comment]
Thanks!
