### ISSUE TITLE
NPM Install warning 

### ISSUE THREAD

**Issue by Sneeuwtijger** [t0mg/reacticz#33]
When I perform a NPM install in the Reactiz directory I get the following warning during the install : 
<npm WARN optional dep failed, continuing fsevents@1.0.14>
Then the process runs for 20 minutes and stops.
When running NPM install again I get the following warnings -

npm WARN unmet dependency /home/pi/domoticz/www/reacticz/node_modules/react-scripts/node_modules/jest/node_modules/jest-cli/node_modules/istanbul-api/node_modules/istanbul-reports/node_modules/handlebars/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /home/pi/domoticz/www/reacticz/node_modules/react-scripts/node_modules/jest/node_modules/jest-cli/node_modules/istanbul-api/node_modules/istanbul-reports/node_modules/handlebars/node_modules/async,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /home/pi/domoticz/www/reacticz/node_modules/react-scripts/node_modules/jest/node_modules/jest-cli/node_modules/istanbul-api/node_modules/istanbul-reports/node_modules/handlebars/node_modules/uglify-js requires source-map@'~0.5.1' but will load
npm WARN unmet dependency /home/pi/domoticz/www/reacticz/node_modules/react-scripts/node_modules/jest/node_modules/jest-cli/node_modules/istanbul-api/node_modules/istanbul-reports/node_modules/handlebars/node_modules/source-map,
npm WARN unmet dependency which is version 0.4.4
npm WARN unmet dependency /home/pi/domoticz/www/reacticz/node_modules/react-scripts/node_modules/jest/node_modules/jest-cli/node_modules/istanbul-api/node_modules/istanbul-reports/node_modules/handlebars/node_modules/uglify-js requires yargs@'~3.10.0' but will load
npm WARN unmet dependency /home/pi/domoticz/www/reacticz/node_modules/react-scripts/node_modules/jest/node_modules/jest-cli/node_modules/yargs,
npm WARN unmet dependency which is version 6.6.0

Should I take any action ?

**Comment by t0mg** [comment]
Thanks for the report. I noticed these warnings too, I don't think that they affect Reacticz, but let me know if you are unable to build it. I'll try to resolve these eventually.

**Comment by Sneeuwtijger** [comment]
A npm start results in an error  : 


sh: 1: react-scripts: not found

Failed at the reacticz@0.1.2 start script 'react-scripts start'.

I think the build has failed, somehow - delete directory, git clone again and try the build again?
Running on a PI 3, fyi

**Comment by t0mg** [comment]
Yeah ok so these warnings are actually not good. Make sure node and npm are up to date. Mine are 7.3.0 (6.9 is also fine) and 3.10.10. respectively. Then delete your node-modules and try again. If all fails, you can still grab the pre-built version of Reacticz from the gh-pages branch (just remove the analytics snippet in the index.html).

**Comment by Sneeuwtijger** [comment]
My node is 2.14.7, tried to upgrade it - problem with npm - removed npm, problem with nodejs, removed nodejs, installed npm - now tried to re-install node - still version 2.14.7 - I think I am taking your suggestion and grab the pre-built version, thx

**Comment by t0mg** [comment]
Pre-built version won't work from the www subfolder of Domoticz unfortunately. You could either build it from a desktop computer with node and npm, or ask for someone else's files on the forum...

**Comment by Sneeuwtijger** [comment]
Hmmm, building it on a desktop computer - I was just getting used to my PI - will it run in nginx root folder?

**Comment by NietGiftig** [comment]
I'm running linux (mint 17.3) on my desktop
my node version is v6.9.4
checked with
 `node -v`

**Comment by Sneeuwtijger** [comment]
Good suggestion - I will try that and port it to the Pi, thx ;)

**Comment by t0mg** [comment]
Yes ngnx should be fine. It's just static files.

If you build it, don't forget to update the package.json with the url path
you'll be using (if your not using the webserver root). Good luck!

Le lun. 23 janv. 2017 à 01:04, Sneeuwtijger <notifications@github.com> a
écrit :

**Comment by Sneeuwtijger** [comment]
Thx for the info - I did a 'git clone' of the gh-pages branch into the root of nginx - works like a charm.
Problem solved.

**Comment by t0mg** [comment]
Thanks, closing the issue.
