### ISSUE TITLE
Unsupported type: RFXMeter counter

### ISSUE THREAD

**Issue by papo-o** [t0mg/reacticz#36]
{"Battery":255,"RSSI":12,"description":"","dtype":"RFXMeter","id":"82153","idx":154,"name":"Compteur Eau Froide","nvalue":0,"stype":"RFXMeter counter","svalue1":"104770","unit":1}
![eau_froide2](https://cloud.githubusercontent.com/assets/25136535/22266597/df86ef90-e280-11e6-9673-ed8657bf159a.png)

json request result
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
Counter: "104.810 m3",
CounterToday: "240 Liter",
CustomImage: 0,
Data: "104.810 m3",
Description: "",
Favorite: 1,
HardwareID: 14,
HardwareName: "Capteurs Virtuels",
HardwareType: "Dummy (Does nothing, use for virtual switches only)",
HardwareTypeVal: 15,
HaveTimeout: false,
ID: "140E9",
LastUpdate: "2017-01-24 22:00:18",
Name: "Compteur Eau Froide",
Notifications: "false",
PlanID: "4",
PlanIDs: [
4
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "RFXMeter counter",
SwitchTypeVal: 2,
Timers: "false",
Type: "RFXMeter",
TypeImg: "counter",
Unit: 1,
Used: 1,
ValueQuantity: "",
ValueUnits: "",
XOffset: "276",
YOffset: "401",
idx: "154"
}

**Comment by t0mg** [comment]
seriously @papo-o , how many sensors do you have ? :)

**Comment by deennoo** [comment]
if papo-o is lake me i made his home full automated !

got : 375 devices (bulb, switch, group, scene, utility, virtual, media, pir).

best option for you @t0mg is too add all devices aviable !

**Comment by papo-o** [comment]
i have 125 devices now but i hope add more soon

**Comment by t0mg** [comment]
I have a little problem with this one. RFX meter counter can be of several types (gas, water, energy, etc) but it seems that the unit doesn't appear in the mqtt message. When I change the type, nothing changes in the message (unit is always 1)...

**Comment by papo-o** [comment]
i write a issue on domoticz forum
https://www.domoticz.com/forum/viewtopic.php?f=6&t=15902#p118120

**Comment by papo-o** [comment]
gizmocuz response

> the unit is a second identification of the unique device id.
> For instance a remote AC) kan have the same ID, but has 4 buttons, for unit id's

**Comment by papo-o** [comment]
can you use the description for units? 
`{"Battery":255,"RSSI":12,"description":"kWh","dtype":"RFXMeter","id":"82197","idx":198,"name":"Compteur Lumières","nvalue":0,"stype":"RFXMeter counter","svalue1":"3690425","unit":1}`
`{"Battery":255,"RSSI":12,"description":"m3","dtype":"RFXMeter","id":"82155","idx":156,"name":"Compteur Gaz","nvalue":0,"stype":"RFXMeter counter","svalue1":"213175325","unit":1}`

**Comment by t0mg** [comment]
If I have to, yes I can do that. Gizmocuz doesn't seem like he intends to fix the MQTT messages anyway 😞

**Comment by papo-o** [comment]
no he doesn't

**Comment by papo-o** [comment]
my new question
`in this case, How can we identify the units counter in mqtt?`
gizmocuz new response
`It is the 'stype'
If you edit your sensor, change it to a 'water' meter for a water meter, and 'gas' for gas
Now you have set them all as counter... how would you differentiate it now ? Only by name ? Then this is the option you could use also in your MQTT
But i advise to set the sensors to the correct type`

**Comment by papo-o** [comment]
but stype doesn't display the right type, only RFXMeter counter

**Comment by gerard33** [comment]
Gizmocuz already implemented this :)
https://www.domoticz.com/forum/viewtopic.php?f=6&t=15902#p118147

**Comment by t0mg** [comment]
Oh wow that was fast! Awesome news! I'll get on to it when the beta is released.

**Comment by papo-o** [comment]
the beta is release
`{"Battery":255,"RSSI":12,"description":"","dtype":"RFXMeter","id":"82319","idx":320,"meterType":"Water","name":"Compteur Eau Chaude","nvalue":0,"stype":"RFXMeter counter","svalue1":"577259","unit":1}`

**Comment by t0mg** [comment]
Ok folks here's a first version, with the latest beta Reacticz picks up the unit type. Otherwise it'll just show the raw data without any unit. The meter widget looks like this:
![meter](https://cloud.githubusercontent.com/assets/1903597/22620080/e483c6ea-eb03-11e6-932a-c1c712fd3ed9.png)
(except if the type is gas because we already have a dedicated GasWidget for that).

The reason why I didn't reuse the Watt widget here (the one with the plug) is because WattWidget is primarily for instant consumption (power in watts) and RFXMeter is a counter (energy in kWh).

**Comment by NietGiftig** [comment]
> The reason why I didn't reuse the Watt widget here (the one with the plug) is because WattWidget is primarily for instant consumption (power in watts) and RFXMeter is a counter (energy in kWh).

Perfect, but now have to update my Domoticz.
Iḿ always waiting with that until I see little changes in the GIT, but that is not today

**Comment by t0mg** [comment]
Not sure I'm following. You don't need to update Domoticz right now: if you have a RFXMeter device, it will just not show the unit. If that's OK with you as an intermediary solution, then you can leave it like that and update Domoticz only when the next stable release comes.

**Comment by NietGiftig** [comment]
I know, I only update Domoticz if something that I like is new included, I'm not waiting for stable releases.
This is such a change.
But there were many more changes in Domoticz the last couple of days.
And I'm always trying to wait until the dust has settled so to say.

**Comment by t0mg** [comment]
Yeah same here ;) I switched to beta channel after Harmony supoort stopped working...

**Comment by papo-o** [comment]
can you personalise water widget like gas widget?

**Comment by t0mg** [comment]
Sure but I need an icon for that. From I could only find this one: https://material.io/icons/#ic_local_drink

This other one would've been nice: https://material.io/icons/#ic_opacity but it's already used for rain gauge.

**Comment by papo-o** [comment]
perhaps this  http://www.iconsdb.com/custom-color/water-icon.html with Custom color #ABABAB

**Comment by t0mg** [comment]
We'd need an icon in svg format though. Maybe we can go with https://material.io/icons/#ic_invert_colors ?

**Comment by papo-o** [comment]
like this ?
https://www.americanstandard-us.com/-/media/sites/asus/images/icons/water.svg

**Comment by Sneeuwtijger** [comment]
Site materialdesignicons.com has a nice collection of material icons, search on 'water' and keeping the water tap idea I would suggest this one https://materialdesignicons.com/api/download/icon/svg/06862D93-608A-4B21-9193-83FA8C6BBDCD

**Comment by t0mg** [comment]
Yes materialdesignicons.com is a great source, it has all the base Google icons and then some. And people can contribute with new ones. I didn't expect Reacticz to need that many icons (I don't really use sensors) but we keep adding icons and we're starting to have quite a bit. I think it's time for some refactoring. I'll switch the icons system over to materialdesignicons.com whenever I can.
