### ISSUE TITLE
Thermostat support

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#4]
Is it possible to add support for a thermostat?
Currently I get the following message.
`Unsupported type:
{"Battery":255,"RSSI":12,"dtype":"Thermostat","id":"0000001","idx":283,"name":"Thermostaat","nvalue":0,"stype":"SetPoint","svalue1":"17.00","unit":0}`

The JSON output from Domoticz is
`{
   "ActTime" : 1483917488,
   "ServerTime" : "2017-01-09 00:18:08",
   "Sunrise" : "08:44",
   "Sunset" : "16:41",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "17.0",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 15,
         "HardwareName" : "Thermostaat",
         "HardwareType" : "ICY Thermostat",
         "HardwareTypeVal" : 28,
         "HaveTimeout" : false,
         "ID" : "0000001",
         "LastUpdate" : "2017-01-09 00:17:34",
         "Name" : "Thermostaat",
         "Notifications" : "false",
         "PlanID" : "20",
         "PlanIDs" : [ 20 ],
         "Protected" : false,
         "SetPoint" : "17.0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "false",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "283"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

**Comment by t0mg** [comment]
@gerard33 I am not familiar with thermostat devices, what is the expected interface ? Is it read only or can we set a value ? I can't find the related commands in the [JSON API documentation](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's).

**Comment by gerard33** [comment]
You can set a value in Domoticz by changing the setpoint in steps of 0.5 degrees (or 1 degree).
The JSON command is /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=TEMP

Seems it is not supported by MQTT.
I also use eDomoticz plugin to control Domoticz with Siri. They use MQTT as well, but the thermostat setpoint is set using the JSON command.
[https://github.com/PatchworkBoy/homebridge-edomoticz/blob/master/lib/domoticz_accessory.js#L393](url)

**Comment by t0mg** [comment]
@gerard33 please reopen the ticket if it doesn't work for you... I'm a little bit in the dark on this one :)

**Comment by gerard33** [comment]
@t0mg the thermostat widget works great! Thanks!

Only thing is that it shows the temp in 2 decimals (e.g. 17.50) where 1 is sufficient (and taking less room on a phone). I will have a look at it and see if I can change that.
