### ISSUE TITLE
Unsupported type: Gas

### ISSUE THREAD

**Issue by pservais** [t0mg/reacticz#40]
{"Battery":255,"RSSI":12,"dtype":"P1 Smart Meter","id":"1","idx":124,"name":"Gasverbruik","nvalue":0,"stype":"Gas","svalue1":"7411968","unit":2}

JSON result:
{
   "ActTime" : 1485622076,
   "ServerTime" : "2017-01-28 17:47:56",
   "Sunrise" : "08:19",
   "Sunset" : "17:20",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "7411.968",
         "CounterToday" : "7.424 m3",
         "CustomImage" : 0,
         "Data" : "7411.968",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 19,
         "HardwareName" : "P1 smartmeter",
         "HardwareType" : "P1 Smart Meter USB",
         "HardwareTypeVal" : 4,
         "HaveTimeout" : false,
         "ID" : "1",
         "LastUpdate" : "2017-01-28 17:45:14",
         "Name" : "Gasverbruik",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Gas",
         "SwitchTypeVal" : 1,
         "Timers" : "false",
         "Type" : "P1 Smart Meter",
         "TypeImg" : "counter",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "124"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by t0mg** [comment]
Could you suggest an icon for this widget, from the list available at https://material.io/icons/ ?

**Comment by pservais** [comment]
I would suggest 'Whatshot', the flame image relates to the gas used to burn a stove etc.

**Comment by pservais** [comment]
Can you change the displayed data from Data to Countertoday? This value is more in sync with the energy widget which also displays a current/today value.

**Comment by t0mg** [comment]
Unfortunately no, for some reason the data/couner is the only information available in the MQTT message. Same as in the JSON API: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Gas

**Comment by pservais** [comment]
'Tears in my eyes'... I will post a request to the Domoticz devs for this.

**Comment by t0mg** [comment]
Please do! :)

**Comment by pservais** [comment]
Done! :)
