### ISSUE TITLE
Selector switch support

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#5]
Is it possible to support the Domoticz selector switches?

![selector switch](https://cloud.githubusercontent.com/assets/11230573/21754481/77472a98-d601-11e6-9727-8046e882f2d7.jpg)
![selector switch 2](https://cloud.githubusercontent.com/assets/11230573/21754507/2c1d8c32-d602-11e6-9eb5-9a776c9833aa.jpg)

The JSON output from Domoticz
`{
   "ActTime" : 1483917547,
   "ServerTime" : "2017-01-09 00:19:07",
   "Sunrise" : "08:44",
   "Sunset" : "16:41",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "Selector voor lamp kantoor (idx 376)",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01000000",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-12-20 16:46:34",
         "Level" : 0,
         "LevelActions" : "http%3A//127.0.0.1%3A8084/json.htm%3Ftype%3Dcommand%26param%3Dswitchlight%26idx%3D376%26switchcmd%3DOff|http%3A//127.0.0.1%3A8084/json.htm%3Ftype%3Dcommand%26param%3Dswitchlight%26idx%3D376%26switchcmd%3DSet%2520Level%26level%3D41|http%3A//127.0.0.1%3A8084/json.htm%3Ftype%3Dcommand%26param%3Dswitchlight%26idx%3D376%26switchcmd%3DSet%2520Level%26level%3D61|http%3A//127.0.0.1%3A8084/json.htm%3Ftype%3Dcommand%26param%3Dswitchlight%26idx%3D376%26switchcmd%3DSet%2520Level%26level%3D100",
         "LevelInt" : 0,
         "LevelNames" : "Off|40|60|100",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Lamp kantoor (selector)",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 10,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "337"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

**Comment by NietGiftig** [comment]
Thanks for taking the time to request this one, you have my vote

For me I see this Reacticz GUI as replacement for the Domoticz GUI on my tablets.
On tablets the use of the Domoticz GUI is often touch and fail with the selector switch.
My fingers are simply to big or to much trembling. ;-)
I use the selector switch in both modes Button and List.
Most important (for me that is) that the list mode pops up a list with somewhat bigger layout compared to the Domoticz lists.
So in this case functionality over beauty

**Comment by t0mg** [comment]
This is a first iteration, feedback welcome. Note that the current implementation lacks the device name in toggle button mode, I still need to figure out an elegant way to show it.

**Comment by gerard33** [comment]
It's working great.
Maybe you can place the device name on top of the buttons (just as for the temp sensor) and make these buttons a little lower, so the total height is the same?
