### ISSUE TITLE
Rain gauge

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#54]
I have to do some extra checks to see if the data in the rain gauge from #53 is right.
I tested it with when there was no rain, but I am not sure if MQTT is sending the proper data for a rain gauge. I have 2 rain gauges (one actual device and one from Weather Underground) and the data seems inconsistent.

Will do some more testing once it rains again ;)

**Comment by t0mg** [comment]
OK thanks for the ticket. I am afraid that I can't help you much on this one :)

**Comment by gerard33** [comment]
Fixed in #60

**Comment by Sneeuwtijger** [comment]
Rain Gauge, Wunderground, displayed the amount of rain - 10mm / hour - last Sunday - i think it was right at that time - but the total value for the day stayed at 0 where in Domoticz this Rain Gauge displayed the correct value of 2mm

**Comment by gerard33** [comment]
@Sneeuwtijger can you send me some details once it has rained again?
- JSON output from the device in Domoticz
- Screenshot of the rain gauge in Domoticz and Reacticz
- Prefarably also the MQTT output
Then I can compare it with my own data and see if I need to change some more.

The rain gauge from Weather Underground is working fine in Reacticz over here.

**Comment by Sneeuwtijger** [comment]
I only have the Weather Underground rain gauge, yesterday evening it was snowing and values in Domoticz and Reacticz where equal - as you already found out ;) 
So, no problems at my side anymore.

**Comment by gerard33** [comment]
Will close this issue.
When you have a rain gauge device of stype TFA you will only get the total value visible.
If that is a problem, we need to make a request to change the MQTT message from Domoticz.
