### ISSUE TITLE
Thermostat

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#55]
@t0mg, just wondering if it is possible to change the behaviour of the thermostat widget a bit.

Currently every press on the button of the widget sends a command directly.
This means that if you set the thermostat from 18.5 to 17.0 there are 3 commands send, as the Domoticz log below shows.

`2017-02-04 00:26:52.223 ICYThermostat: Setting Room SetPoint to: 17.0
2017-02-04 00:26:51.996 Sending SetPoint to device....
2017-02-04 00:26:51.983 ICYThermostat: Setting Room SetPoint to: 17.5
2017-02-04 00:26:51.316 Sending SetPoint to device....
2017-02-04 00:26:51.031 ICYThermostat: Setting Room SetPoint to: 18.0
2017-02-04 00:26:50.787 Sending SetPoint to device....`

I think it would be more logical to use the same way as Domoticz changes the setpoint.
![setpoint](https://cloud.githubusercontent.com/assets/11230573/22612776/2e6621b8-ea73-11e6-988e-01eaa079d5af.png)

So you first select the right temp and then you click the button to set that temp. This means only one command is being sent.
What do you think?

**Comment by t0mg** [comment]
The way reacticz works is that the interface reflects the state of the devices in real time. Clicking an on off button doesn't change the color if the button, it sends the toggle command and Domoticz returns an MQTT message withe the status update which is received by reacticz, finally updating the state of the button. This ensures that what you see is always in sync with the actual state of the devices (and that makes reacticz faster than the regular dashboard or even the mobile app). So with the thermostat I understand your concern but decoupling the value of the widget from the true state of the device is something I'm not super found of. However, there is one exception : on dimmer switch I do some throttling to limit the number of commands reacticz sends, this is why there is a bar that gives immediate feedback, and the progress thing behind is a bit late behind but reflects what Domoticz actually sends back. We could implement something similar on the thermostat, for example using an alternative color for the temperature when it's being changed, then wait for a little delay and send the command. When the "true" value comes back from Domoticz the widget would switch back to regular color.

**Comment by gerard33** [comment]
That sounds like an excellent solution!

**Comment by t0mg** [comment]
I chose to make it blink instead of change color, this avoids adding a new color in the theme just for that, and is a familiar pattern when setting digital clocks and counters.

**Comment by gerard33** [comment]
Very nice! Thanks for implementing.
Works great this way :)
