### ISSUE TITLE
Weather widget

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#56]
@t0mg, what do you think about adding some icons in the weather widget for:
- temp
- temp + hum
- hum only

Maybe https://material.io/icons/#ic_wb_sunny can be used for temp and temp + hum.
And https://material.io/icons/#ic_opacity for hum only?

And that the image turns to 'on' when certain temp or hum is exceeded?

I think then this is more in line with the GenericWidget approach.

![weatherwidget](https://cloud.githubusercontent.com/assets/11230573/22613300/847ae3d2-ea77-11e6-96b8-077fb6180e4b.png)

**Comment by t0mg** [comment]
Yes it's probably better to route these to another different widget using
GenericWidget. Feel free to give it a shot :)

The opacity icon would be nice on the rain meter widget too ("local drink"
too), and maybe "graphic eq" or "blur on" for humidity (because it sorta
looks like fog) ?

**Comment by gerard33** [comment]
Allright, I'll give it a try.
And keep the temp + hum + baro in the WeatherWidget then?

**Comment by Sneeuwtijger** [comment]
I would like the Weather widget with temp + hun + baro to stay ;) one overview gives all the info.
One thing - if it is dark the Weather Widget still gives cloudy + sun which should be cloudy + moon - should I open a separate ticket for this?

**Comment by gerard33** [comment]
That will stay for sure, it's just adapting some code so the weather widget has the same layout as e.g. the wind widget using GenericWidget :)

**Comment by t0mg** [comment]
Regarding the nighttime weather visuals, I couldn't find nice, free visuals matching the Material Design style, and didn't have time to try to make some myself. So for now I'm looking at my watch or  window to figure out whether it's dark outside ;) To me this is still better than poorly looking (or stolen) visuals. @Sneeuwtijger please file a separate ticket requesting nighttime weather images, I'll give it a shot.

@gerard33 regarding the WeatherWidget, it could possibly be entirely refactored using several GenericWidgets but I thought you only wanted to add icons on devices that don't have barometric information. If you also rewrite the code for the widget with baro, please note that the weather forecast images are larger than the icons (basically the image/text ratio is intentionally different from the GenericWidget).

**Comment by gerard33** [comment]
@t0mg, then I will leave the baro in the WeatherWidget and make a new widget for temp, hum and temp + hum. That new widget will then be using the GenericWidget.

**Comment by t0mg** [comment]
Sounds good to me !

**Comment by Sneeuwtijger** [comment]
Issue #59 submitted for night time imagea

**Comment by gerard33** [comment]
Move temp, hum, hum + temp in #60.
