### ISSUE TITLE
Error message if there is no floorplan defined in Domoticz

### ISSUE THREAD

**Issue by davidlb** [t0mg/reacticz#57]
On the device list, there is a an error message "Unable to reach Domoticz server" if there is no floorplan defined. Everything else works fine.

Excellent work, I really like it!

**Comment by t0mg** [comment]
Hi there. Are you sure that's the reason? I can't reproduce the issue at home even though I don't have any floorplans either.

**Comment by davidlb** [comment]
I'm not sure but it seems to be related. I'm running Domoticz Beta v3.6591 on Rasp Pi

Chrome console: 
Unable to reach Domoticz TypeError: Cannot read property 'length' of undefined
    at RoomplanSelector.js:46
    at JSONClientSingleton.js:65

And the Json response associated:
{
   "status" : "OK",
   "title" : "Plans"
}

**Comment by davidlb** [comment]
In fact, it's related to scene. A control as you did for plan is missing:
      if (!data.result) {
        return;
      }

**Comment by t0mg** [comment]
Ah nice catch. I do have scenes, that's why I never noticed the issue. Thanks for fixing it yourself.
