### ISSUE TITLE
Night time images for the Weather Widget

### ISSUE THREAD

**Issue by Sneeuwtijger** [t0mg/reacticz#59]
Requesting night time images for the Weather Widget, I will also search myself for material style night time images.

**Comment by gerard33** [comment]
See this link from the same author.
https://plus.google.com/+KevinAguilarC/posts/E9BFv6fyfMz

**Comment by Sneeuwtijger** [comment]
I found these set of icons  [https://erikflowers.github.io/weather-icons/] (url) and i also think Wunderground Weather itself returns an icon link with the Weather but I do not think this is available in Domoticz

**Comment by t0mg** [comment]
@gerard33 these are not free :) But it's pretty cheap and I like them better than the icon set @Sneeuwtijger found because they have some color and paper-like design.

**Comment by t0mg** [comment]
This issue was moved to domoticz/Reacticz#4
