### ISSUE TITLE
Icon missing in main Reacticz bar in Edge on Windows 10

### ISSUE THREAD

**Issue by Sneeuwtijger** [t0mg/reacticz#61]
When running Reacticz in Edge on Windows 10 the 3rd button on the main bar is missing, see attached image
![reactiz windows 10 edge icon missing](https://cloud.githubusercontent.com/assets/24943584/22648007/bbb2f07a-ec74-11e6-98b6-6fefab13277d.png)

**Comment by t0mg** [comment]
Ha funny one. I'll need to find a windows computer before I can figure this one out...

**Comment by Sneeuwtijger** [comment]
Yup, funny it is, Edge is not playing nice I think, just as IE was in earlier days - if you need information - I am familiar with CSS and other web coding, feel free to ask

**Comment by gerard33** [comment]
I see I have the same issue in Internet Explorer 11 on Windows 7. Never tested with IE until now, I and also know why again :)

Looks like IE has trouble with the SVG in the index.html.
The error message in the console is HTML1500 and related to self-closing tags.
http://stackoverflow.com/questions/24299969/closing-svg-tags-explicit-or-self-closing
I will see if I can do some tests on this.

There is also a SEC7119 CORS error in the console.
http://stackoverflow.com/questions/20198696/cors-request-with-ie11

**Comment by gerard33** [comment]
There is also a SEC7119 CORS error in the console with Internet Explorer.
http://stackoverflow.com/questions/20198696/cors-request-with-ie11

Will have a look at that as well.

**Comment by t0mg** [comment]
This icon was rather complex, using a clippath. I've replaced it with simpler svg in commit 5e8dcf0 (just one path), let me know if it works better in IE/Edge.

**Comment by gerard33** [comment]
Yes that works (in IE11 at least). Will update the contact closed icon the same way.

**Comment by t0mg** [comment]
Thanks, I think we can close this one now :)

**Comment by Sneeuwtijger** [comment]
Problem solved - check on Edge in Windows 10
