### ISSUE TITLE
Unsupported type : UV Index

### ISSUE THREAD

**Issue by Sneeuwtijger** [t0mg/reacticz#67]
Error on including UV - available from Weather Underground

{"Battery":255,"RSSI":12,"dtype":"UV","id":"1","idx":48,"name":"UV","nvalue":0,"stype":"UVN128,UV138","svalue1":"0.0","svalue2":"0.0","unit":0}
![reacticz issue - uv index](https://cloud.githubusercontent.com/assets/24943584/22745446/dd4b2cd6-ee20-11e6-9e17-3d73614f866c.png)

**Comment by gerard33** [comment]
@t0mg you can assign this one to me. I have this sensor as well, so can easily do some testing.
Will also add the Visibility sensor and Solar Radiation sensor which are also part of the weather devices.

**Comment by Sneeuwtijger** [comment]
Thank you @gerard33 - the other ones are missing also - i am a coder by trade but have not done any work in this area - git is also a mystery to me - cloning is all i know ;)

**Comment by t0mg** [comment]
Cool. I can't assign you @gerard33 but I take good note. Just don't try too hard to find an icon in material.io/icons/ on this one, as we'll soon be switching over to materialdesignicons.com where there is a little more choice :)

**Comment by gerard33** [comment]
Made pull request #71.

Took the liberty to already add some icons from materialdesignicons.com.
I have added comments to the svg's in index.html to show which icons are from that site.

I know the svg method is still under investigation, but at least the choice of the icons is already done ;)

**Comment by Sneeuwtijger** [comment]
@gerard33 nice work, I like the icon choice - especially the sun glasses on UV Index lol
