### ISSUE TITLE
Initial state wrong?

### ISSUE THREAD

**Issue by felix63** [t0mg/reacticz#73]
When I start Reacticz a dimmer is shown using the dimmed value (partly colored) even if the dimmer is off. When the dimmer is turned on and then off in Reacticz the dimmer is shown as gray.
<img width="326" alt="scherm2" src="https://cloud.githubusercontent.com/assets/16501940/22808372/daf04b22-ef2b-11e6-953b-bb37138c7d32.png">
<img width="232" alt="scherm1" src="https://cloud.githubusercontent.com/assets/16501940/22808373/db210a14-ef2b-11e6-95ec-7febfa6aca5f.png">

**Comment by t0mg** [comment]
I think it happens to me too. I believe it's due to domoticz which gets out of sync (it also shows the wrong value when I open the domoticz dashboard). I'll double check that but if I'm correct I'm afraid there isn't much that can be done on reacticz side...

**Comment by felix63** [comment]
With me the domoticz switch is a correct reflection of the lamp state. It's just reacticz that seems to be off.

**Comment by t0mg** [comment]
Ok, I'll check again then !
