### ISSUE TITLE
Unsupported type: Motion Sensor

### ISSUE THREAD

**Issue by felix63** [t0mg/reacticz#74]
I have several motion sensors that seem to be unsupported. {"Battery":255,"RSSI":12,"description":"","dtype":"Light/Switch","id":"00003C35","idx":699,"name":"beweging_studio","nvalue":0,"stype":"Switch","svalue1":"0","switchType":"Motion Sensor","unit":1}

**Comment by gerard33** [comment]
Made a pull request for that in #71 :)
