### ISSUE TITLE
Thermostat keeps blinking after update on thermostat itself

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#76]
Just noticed that the thermostat in Reacticz keeps blinking after it has been updated manualy on the thermostat itself.

This message was sent by MQTT.
`domoticz/out {
   "Battery" : 255,
   "RSSI" : 12,
   "dtype" : "Thermostat",
   "id" : "0000001",
   "idx" : 283,
   "name" : "Thermostaat",
   "nvalue" : 0,
   "stype" : "SetPoint",
   "svalue1" : "17.00",
   "unit" : 0
}`

The previous svalue1 was 20.00 and the thermostat in Reacticz keeps blinking at 20.0.
After a page refresh the right value of 17.0 is being showed.

**Comment by t0mg** [comment]
I didn't think of that :) I'll try to fix it!

**Comment by gerard33** [comment]
Thanks, it is working fine now.
