### ISSUE TITLE
RGBW switches color/dim

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#8]
The color of a RGBW light can be changed, but on iOS this is not working well as you have to enter the hex code. See the screenshot below from my iPhone.
![rgbw light](https://cloud.githubusercontent.com/assets/11230573/21786109/c7e3aeba-d6c2-11e6-9215-6e2560237391.jpg)

My suggestion would be:
- make an option if you want to be able to change the color of a RGBW light in the devices selection
  - if no, than don't show the color changer for that device

And I noticed that a RGBW light can not be dimmed. Is it possible to add that function?

**Comment by t0mg** [comment]
I think I need to replace the native HTML color picker with something that will look the same on all devices. 

Regarding dimming you can simply select a darker color, my intention is for each widget to have as little buttons as necessary - I want to avoid turning the dashboard into a scientific calculator. Besides you can use scenes or a selector switch if you want quick access to specific color values.

**Comment by gerard33** [comment]
I totally agree to keep the dashboard as clean as possible.
Only thing is that the dimmer function is not creating an extra button.

The native color picker seems to be a good idea.

**Comment by t0mg** [comment]
> The native color picker seems to be a good idea.

Well that's what it's currently using :) It works well on Chrome and Android, but it seems like it's bad on iOS. Maybe I should provide an alternative for iOS only then...

**Comment by NietGiftig** [comment]
> The native color picker seems to be a good idea.
It a deviation from the total layout, but for the time being...., if it works!
Later on something more suiteble in layout.

**Comment by gerard33** [comment]
Didn't read your remark regarding the native color picker correctly :)
If an alternative for iOS is possible then that would be nice.

And do you think it is possible to add the dim function as well by swiping on the name of the switch just as with a normal dimmer?

**Comment by t0mg** [comment]
Might be doable although I think it would be hard to control in the default size. Simply setting a dark color does the trick for me on Hue lights. I still think a selector switch would possibly be a better solution for quick accessing preset custom colors. I'll consider a custom solution for iOS but this is low priority to me (not to mention that it's going to be hard to develop since I don't have any iOS devices at home :) ).

**Comment by deennoo** [comment]
really a great job ! 

about rgbw device, can you add a return to white fonction please ?

**Comment by t0mg** [comment]
@deennoo I'll keep this in mind when I'll rewrite this widget. I need to investigate more on how to provide a good experience to everyone including iOS ;)

**Comment by t0mg** [comment]
Giving some love to the oldest open issue! Commit 8d5fa6c introduces a new widget for this. After trying out different things ([like these](https://casesandberg.github.io/react-color/)) I realized that this wasn't really adapted to the use case of picking colors for lighting. So I made one from scratch that hopefully is easier to use. It looks like this:

![rgbw](https://cloud.githubusercontent.com/assets/1903597/23048250/e35cffce-f4b4-11e6-8dd9-8f6adb5c6bb7.png)

On the left is the toggle button, just like before. On the top right row is a hue bar allowing to select a hue (tap/click only, swipe not supported yet). Doing this doesn't update the lamp yet, instead it updates the swatch on the second row:

![rgbw2](https://cloud.githubusercontent.com/assets/1903597/23048276/100aea86-f4b5-11e6-8658-48929c055d18.png)

Then a single tap on the second row allows to pick the desired level of brightness and send the update to Domoticz. The last button on the right is a "return to white" (it also restores the swatch as it is in the first screenshot).

With this pattern, it is possible to select a color and brightness with just two or three taps and no popup. I hope you'll like it, I'd love to read your feedback on this.

Cheers!

**Comment by gerard33** [comment]
That is looking great!
Will try it this weekend and let you know the feedback.

**Comment by t0mg** [comment]
This rainbow gradient is actually hurting my eyes, I think I'll mute it a little.

**Comment by NietGiftig** [comment]
It is by all means a colorful addition, no matter how intense ;-)
I have a question (not related to reacticz)
I have node-red subscribed to domoticz/in & out for some not supported self made LED devices.
Where in the mqtt message to Domoticz is the color-hex and Brightness hidden?
Maybe this question gives an insight in my complete noobisch knowledge.

**Comment by t0mg** [comment]
New commit 14d9554 add some refinements:
- margins and and other tweaks for readability consistency with other widgets (blinds, selector)
- a new "mini" mode: when the widget has a width of 1 on the grid, only the toggle button is shown. I think it's pretty cool and maybe we should implement that on the GenericWidget (this would hide the icon).
- muted the hue bar a little

Below are 2 RGBW devices, the first one with default width, the second one in "mini" mode.

<img width="249" alt="screen shot 2017-02-17 at 9 52 39 pm" src="https://cloud.githubusercontent.com/assets/1903597/23083000/1317c922-f55c-11e6-9127-4a06188e2e42.png">

**Comment by gerard33** [comment]
Nice, it's working great on my desktop, the mini mode as well.

But iOS continues to cause hassle :(
This is the RGWB widget on iOS. On/off is working, but no color bars. Also the mini mode is not working.
![rgbw](https://cloud.githubusercontent.com/assets/11230573/23084300/f475827e-f561-11e6-889f-de3fef6fee2a.png)

**Comment by t0mg** [comment]
Haha ok thanks for the feedback I'll try to fix iOS ;)

**Comment by felix63** [comment]
On Safari 10.0.3 on OS X Sierra 10.12.3 it looks wel, not quite okay...
<img width="421" alt="iris" src="https://cloud.githubusercontent.com/assets/16501940/23085080/ed1ebc62-f565-11e6-86e1-e17cb6b03db8.png">

**Comment by t0mg** [comment]
Thank you @felix63 - I fixed it for both Safari iOS and OS X, and also checked with Firefox. It should look like my screenshot for everyone now (well, except for IE/Edge which I can't test).

**Comment by t0mg** [comment]
@NietGiftig regarding your question on color value and MQTT: unfortunately this is another example where we're short on device information (via MQTT or otherwise for this matter). All we know from MQTT is whether the device is on or off (this is reflected in the state of the toggle button). The rest is write-only: we just send color commands through the JSON API, hoping something will happen... we have no idea what the current color really is – and if that's any indication neither does the Domoticz dashboard (at least in my case).

**Comment by gerard33** [comment]
It's working now on iOS indeed and also on IE11 :)
Nice job!

**Comment by t0mg** [comment]
Thanks for checking @gerard33 
One more change: commit 9c94e99 adding slider behavior to the hue bar, by making the slider logic of the dimmer widget reusable. I tested in iOS emulator it should work fine.

**Comment by gerard33** [comment]
I can confirm this works on iOS :)
Only thing is that the selection option on iOS is enabled when sliding the hue bar. Made issue #92 for that.

**Comment by t0mg** [comment]
Thanks. I've recently inverted the hue bar and the swatch bar because this way it's easier to see the selected color as we swipe the hue bar. 

Closing the issue now!

**Comment by davidlb** [comment]
New widget screenshot (for wiki): 
![image](https://cloud.githubusercontent.com/assets/12050155/24117690/80f5527c-0dab-11e7-8e09-a08a40012e7b.png)

**Comment by t0mg** [comment]
Thanks for the updates!
