### ISSUE TITLE
Multiple Configurations on Single Device

### ISSUE THREAD

**Issue by steps39** [t0mg/reacticz#80]
I would like to be able to have several configurations on a single device, I thought of using a symlink so that the path would be different, but this doesn't work as localstorage ignores path only dependent on domain and protocol.

The symlink idea could work if the localstorage stored information for each path - so normally http://domoticzIP:8080/reacticz/, but http://domoticzIP:8080/reacticz-night/ would store its own information in localstorage - so each path would display its own unique information.

Probably a simpler / cleverer way of achieving the same aim - I guess with setup being purely on the device would be even easier.

**Comment by t0mg** [comment]
With my latest commit, I've added an experimental way to have several configs on the same browser. It is already available on the public server if you want to try. 

Just add ?2 in the url, eg http://reacticz.t0m.fr/?2 and you'll switch to a new empty dashboard. Server and theme settings are shared, but device selection and layout can be adjusted separately. If you want a third dashboard, try adding ?3 :)

You can also add the new dashboards to your homescreen. Let me know if it works for you!

**Comment by NietGiftig** [comment]
wow, working through the night !!
Great result !

**Comment by gerard33** [comment]
That's really great! Working fine over here.

A very nice feature :)

**Comment by steps39** [comment]
Perfect, now I can have a series of buttons on my home screen with very specific (simple) dashboards.

**Comment by steps39** [comment]
I guess I should now close this issue, as I opened it, you enhanced the codeamazingly quickly and it will now go forward with any future releases.  Thanks very much @t0mg nice.

**Comment by steps39** [comment]
iOS behaviour not as I had expected, will Android / Windows mobile be the same?

Strangely if you set up the ?2 or ?3 in Safari on iOS and then "Add to Home Screen" none of the settings saved in localstorage are available to the App on the home screen, no problem you just have to set it up once the button has been created.

Also it turns out for what I want as localstorage is private to each home screen button, that you don't need to have the ?2 as no information is shared between Home Screen apps.

However, on a normal browser this functionality is really useful as you can have different views on the same browser.

But this does mean I can't set up a series of apps for my house and then share them with each of the members of the house as I can only open the export link in the browser, but on creating the Home Screen button no localstorage information is transferred.

So I guess another suggestion for an enhancement will be a different way of sharing setups, with an import in the app if possible.

**Comment by t0mg** [comment]
I see. I think it's different with Chrome on Android, the home screen page is not sandboxed like that, localstorage is shared so it works as expected. Bummer. Another special thing I need to figure out for iOS :( I think you're right, a dedicated field to import settings is the way to go. I'll file a separate ticket for that though.

Thanks everyone for trying the new feature! Still rough on the edges but I think it can be useful. I should probably add a way to clear the data because it's quite easy to clutter localstorage now.

**Comment by t0mg** [comment]
Ok, closed #82  - you should see a new button in the welcome message:

![import](https://cloud.githubusercontent.com/assets/1903597/22863441/402faf30-f140-11e6-8347-01bb6c5188a7.png)

**Comment by steps39** [comment]
Thanks for doing this, definitely a useful feature and as you say another iOS peculiarity.  But :) I wouldn't have suggested the feature if I had not overthought what I was trying to do and just gone ahead on my iPhone.

**Comment by t0mg** [comment]
Well, not a big deal, I can still roll this back if no one thinks it's useful :)
