### ISSUE TITLE
Copying url in About screen in iOS not working

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#84]
Thanks for building #82. This is a very nice feature.
However there is a specific iOS thingy again :(

The field in the About screen with the URL is to small to show the complete URL and it is not possible to select that url.
There is an option in iOS to 'select all' after long press on the text, but then the text above the field is selected.

Maybe you can add a button to copy the complete text in the field?
This link can be usefull http://stackoverflow.com/questions/3272089/programmatically-selecting-text-in-an-input-field-on-ios-devices-mobile-safari.

![ios_about](https://cloud.githubusercontent.com/assets/11230573/22865889/00356fdc-f16d-11e6-932c-9054cc10cb1e.png)

**Comment by t0mg** [comment]
Could you double check that this works on iOS?
https://clipboardjs.com

If it does, I think it would be a better solution than trying to select all or making the field larger.

**Comment by gerard33** [comment]
Yes that works on iOS. Nice solution indeed.

**Comment by t0mg** [comment]
The new cache manifest caused me some trouble. I've removed the CACHE: index.html from it, let me know it it still works for you. Caching this file is counterproductive as the js and css it loads have a name that is unique to the build. When I push a new release the old js and css files are removed as new ones with different file names are being deployed, and the cached index.html points at the old ones, and fails at loading them (since they aren't cached) leading to an empty white screen. We should really cache **nothing** (or... everything).

**Comment by gerard33** [comment]
Copying the URL now works in iOS with the new button :)
I can also paste the url in a new dashboard on the home screen. The all widgets are exactly loaded in the way of the original dashboard.
But when I close the Reacticz web app and the restart it, all the widgets are all alligned in 1 column on the left. So all widgets are still there, but the layout is gone. So when a widget was first 2 columns wide, after reopening it is 1 column wide.

This is the url I used with both the device selection and dashboard layout ticked:
`http://192.168.1.184/reacticz/#N4IgziBcoCYPYFs4BcCWBjAXgQQK7IAsBhAgU3QGtSYoAzAQwBsxSAaEeJNLAGTgHNUAOyggQ7TigyYACvTBgA7nABONSGImIpWAKorGogsmQAHSAHoLARgCcAJgB01gGwAOZ84CsAdkhuABjcAFnEQBABHEzxCEnIqdQZmNnCo5AAhFTgqFX1DDUUwSxsHZ3dPaxDIWwCA6zDIkz5BEQ0GtLkFZTVREABfdmRRABFSBlxGIfZFKABtEH4AHy8wmEWAZnWfVY2HHfsViUX7UKOtgP2Qy-Wd9a83W+t6o8rnjmOg-YDto+DbN7WBxcO2sARWAF12PlZqAZpB7OwCFBrOwAB5QALsACeGPYqFESxWA1hUGCiORaNxIBxkC8eNEa0222JIDhCJASMgKJA6Ph2NJ9I0jL2LLZ5K5lL51IpIHxQuORNYJKlnO5vMx0olsoZx1Coqg7NVkvZNPWgve536StZBvFaqppvNgKu+sgZI5MvV-Klcve9jcN1dhs9DoF2vldweQbtko1NJ8To2TytyuDWt5JqgCfD71eKZtKpDUppLkT9k+0Y96dDkFLOcB33zYqr9uLVN9az+9UrRp5NbcZa8wNd7t7Xs1tkToKJ4L6QA`

I will do some checking on removing the index.html in the cache manifest.
I noticed that when I now press the reload button in the About screen (in a web app on the home screen), it opens a safari browser, where the link previously reloaded the same web app by reloading and showing the widget page. Will probably be something else then the cache manifest.

**Comment by t0mg** [comment]
I already removed the index.html from the manifest :) But there is more investigation to be made. I think the link in the reload button should be replaced with a reload() JS call.

Regarding the missing layout, this looks like a regular bug. If you could reproduce it on a desktop browser, and write down the detailed steps in a new issue, I could try to understand what's going on. I think I've had it myself a couple of times too but I can't recall exactly when.

**Comment by t0mg** [comment]
Ok actually, I think I know about the layout :)
here: https://github.com/t0mg/reacticz/blob/master/src/App.js#L154
we apply the layout from the config but we don't persist it, so if you do not edit the layout manually before reloading reacticz, it will not be saved.
I think this line should be replaced with a call to onLayoutChange(config.l || [])

**Comment by gerard33** [comment]
Shall I make an issue for this change?

**Comment by t0mg** [comment]
Yes, sure. It's easier to track this way :)
