### ISSUE TITLE
Custom sensor

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#89]
Domoticz supports custom sensors which can be used like in the example below.
This sensor is currently not supported in Reacticz yet. I can add it, but have a question regarding the unit.

![custom sensor](https://cloud.githubusercontent.com/assets/11230573/23093042/eb6e9a86-f5d8-11e6-8fab-1e91d52336f3.png)

The MQTT for this sensor is as follows:
`{"Battery":255,"RSSI":12,"description":"","dtype":"General","id":"00082354","idx":355,"meterType":"Energy","name":"Download","nvalue":0,"stype":"Custom Sensor","svalue1":"123.5100","unit":1}`

The unit label (Mbps) is not part of the MQTT. In the JSON it is available under SensorUnit.
`{
   "ActTime" : 1487418101,
   "ServerTime" : "2017-02-18 12:41:41",
   "Sunrise" : "07:46",
   "Sunset" : "17:53",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 136,
         "Data" : "123.51 Mbps",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082354",
         "Image" : "wan",
         "LastUpdate" : "2017-02-18 02:30:26",
         "Name" : "Download",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SensorType" : 1,
         "SensorUnit" : "Mbps",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Custom Sensor",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "wan",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "355"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

I think we can read the SensorUnit from the JSON, but not sure how to do that. Can you point me in the right direction? I have seen some examples in the widgets which use JSON to send commands, but now I only need to read the JSON data.

**Comment by t0mg** [comment]
Yes, you need to add at test [in DeviceWidget](https://github.com/t0mg/reacticz/blob/master/src/widgets/DeviceWidget.js#L34) and call requestDeviceSpec for this device type. Then the information will be available in the widget in props.deviceSpec['SensorUnit']. The deviceSpec requires an extra JSON call which delays the loading of the widget so it should be used only if absolutely necessary. See for example the Selector widget that uses deviceSpec as well (and [shows a loading widget until it's available](https://github.com/t0mg/reacticz/blob/master/src/widgets/SwitchSelector.js#L28)).

**Comment by gerard33** [comment]
Thanks, I think this gives me enough info to give it a try :)
