### ISSUE TITLE
Disable selection option in iOS

### ISSUE THREAD

**Issue by gerard33** [t0mg/reacticz#92]
When sliding on the hue bar in iOS the selection in iOS is triggered.
That means it will select some text on the dashboard, which is not handy ;)
I think the best solution is to prevent this option.
http://sixrevisions.com/css/disable-text-selection/

**Comment by t0mg** [comment]
This is strange, I've already disabled it:
https://github.com/t0mg/reacticz/commit/9c94e99d072db911d5a88c5a19e78a3ea451fa29#diff-669759ffeda41a4dfac15b9427eaeedd

**Comment by gerard33** [comment]
It is selecting text from another widget (contact sensor in this case). I will check that css and disable it there as well to see if that fixes it.

**Comment by t0mg** [comment]
Yeah I see we should disable it globally in this view (but not everywhere in the app)
